# generated by datamodel-codegen:
#   filename:  protocol.json
#   timestamp: 2025-02-25T19:45:35+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, conint


class Point(BaseModel):
    x: int
    y: int


class Detection(BaseModel):
    id: int
    hamming_distance: int
    corners: list[Point]


class Frame(BaseModel):
    camera_name: str = Field(..., description='A unique identifier for the camera.')
    timestamp: int = Field(..., description='The time when the frame was required.')
    markers: list[Detection]
